# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'upload.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

import subprocess
import cv2
import numpy
import os
import shutil
import glob
import tkinter
from tkinter import messagebox as tkMessageBox
# top=Tkinter.Tk()

class Ui_Upload(object):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(9, 9, 699, 461))
        self.widget.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(106, 2, 140), stop:1 rgb(238, 78, 45));\n"
"border-radius: 20px;")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(29, 29, 801, 551))
        self.widget_2.setStyleSheet("background-color:rgba(245, 190, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(60, 60, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 0, 127)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(85, 0, 127)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(120, 100, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(85, 0, 127)")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(560, 20, 20, 20))
        self.pushButton.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 108, 35)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.close)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 180, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(106, 2, 140), stop:1 rgb(238, 78, 45));\n"
"border-radius: 20px;\n"
"color: rgb(255, 170, 255)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.livestream)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_3.setGeometry(QtCore.QRect(230, 300, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(106, 2, 140), stop:1 rgb(238, 78, 45));\n"
"border-radius: 20px;\n"
"color: rgb(255, 170, 255)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_4.setGeometry(QtCore.QRect(230, 360, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(106, 2, 140), stop:1 rgb(238, 78, 45));\n"
"border-radius: 20px;\n"
"color: rgb(255, 170, 255)")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.close)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(480, 410, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_5.setGeometry(QtCore.QRect(230, 240, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(106, 2, 140), stop:1 rgb(238, 78, 45));\n"
"border-radius: 20px;\n"
"color: rgb(255, 170, 255)")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.save)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Surveillance"))
        self.label_2.setText(_translate("Form", "Advanced"))
        self.label_3.setText(_translate("Form", "System"))
        self.pushButton.setText(_translate("Form", "X"))
        self.pushButton_2.setText(_translate("Form", "Show Live Stream"))
        self.pushButton_3.setText(_translate("Form", "Credits"))
        self.pushButton_4.setText(_translate("Form", "Exit"))
        self.label_4.setText(_translate("Form", "Powered By Bits Please"))
        self.pushButton_5.setText(_translate("Form", "Upload More Photos"))
	
    def close(self):
        print('close')
        self.pushButton.clicked.connect(QtWidgets.qApp.quit)


    def livestream(self):
        print('livestream')
        # subprocess.call("important.py", shell=True)
        # os.system('python recognizer.py')
        # working_directory = os.getcwd()
        # file_path = os.path.join(working_directory, 'recognizer.py')

    def credits(self):
        print('cred')

    def save(self):
        src_dir = "C:/Users/Hari/Pictures/test_imagescv/"
        dst_dir = "IR/total_images"
        for jpgfile in glob.iglob(os.path.join(src_dir, "*.jpg")):
            shutil.copy(jpgfile, dst_dir)

if __name__ == '__main__':
        app = QtWidgets.QApplication(sys.argv)
        Form = QtWidgets.QWidget()
        ui = Ui_Upload()
        ui.setupUi(Form)
        Form.show()
        sys.exit(app.exec_())

